// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzrNejV6lsUi15gLXx92FUUOu94Bfz6Hk',
    appId: '1:458572347365:web:971ecf71d2d4cbfc07210c',
    messagingSenderId: '458572347365',
    projectId: 'digidoc-1202a',
    authDomain: 'digidoc-1202a.firebaseapp.com',
    storageBucket: 'digidoc-1202a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDEPJlzk3UbAbbiaqJDnp8tuxftyJi8s',
    appId: '1:458572347365:android:d2f6e92d23377a6607210c',
    messagingSenderId: '458572347365',
    projectId: 'digidoc-1202a',
    storageBucket: 'digidoc-1202a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDt3UcF2O7cshnCSOQdlNotBLD0JaOMWc',
    appId: '1:458572347365:ios:9f2fb11e8d9c009207210c',
    messagingSenderId: '458572347365',
    projectId: 'digidoc-1202a',
    storageBucket: 'digidoc-1202a.firebasestorage.app',
    iosClientId: '458572347365-uvnbors1bfcttne9nf177scgrqoebhbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.codesageuser',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDt3UcF2O7cshnCSOQdlNotBLD0JaOMWc',
    appId: '1:458572347365:ios:9f2fb11e8d9c009207210c',
    messagingSenderId: '458572347365',
    projectId: 'digidoc-1202a',
    storageBucket: 'digidoc-1202a.firebasestorage.app',
    iosClientId: '458572347365-uvnbors1bfcttne9nf177scgrqoebhbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.codesageuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzrNejV6lsUi15gLXx92FUUOu94Bfz6Hk',
    appId: '1:458572347365:web:971ecf71d2d4cbfc07210c',
    messagingSenderId: '458572347365',
    projectId: 'digidoc-1202a',
    authDomain: 'digidoc-1202a.firebaseapp.com',
    storageBucket: 'digidoc-1202a.firebasestorage.app',
  );
}
